<?php

/**
 * Implements hook_preprocess_paragraph().
 *
 * Change referenced entity display.
 */
function os2web_content_reference_paragraph_preprocess_paragraph__os2web_content_reference(&$variables) {
  $paragraph = $variables['paragraph'];

  if ($viewMode = $paragraph->field_os2web_content_ref_vmod->value) {
    $elementsCount = $paragraph->field_os2web_content_reference->count();
    for ($i = 0; $i < $elementsCount; $i++) {
      $content_reference =& $variables['content']['field_os2web_content_reference'][$i];

      if ($content_reference) {
        // Replace view in caching keys.
        $key = array_search($content_reference['#view_mode'], $content_reference['#cache']['keys']);
        $content_reference['#cache']['keys'][$key] = $viewMode;

        // Replace view mode.
        $content_reference['#view_mode'] = $viewMode;
      }
    }
  }
}
