<?php

/**
 * @file
 * Page builder module.
 */

use Drupal\block\Entity\Block;
use Drupal\Component\Utility\NestedArray;
use Drupal\Core\Access\AccessResult;
use Drupal\Core\Form\FormStateInterface;
use Drupal\Core\Session\AccountInterface;
use Drupal\os2web_pagebuilder\Form\SettingsForm;
use Symfony\Component\Yaml\Yaml;

/**
 * Update/creates entity from yml.
 *
 * Some config like form display needs to be updated via config manager.
 *
 * @param string $ymlFileName
 *   Yml file name.
 * @param string $entityType
 *   The entity type for this storage.
 * @param mixed $id
 *   The ID of the entity to load.
 * @param array $setComponents
 *   Array of components you want to add.
 *   - The key will be what we are setting.
 *   - The value is the key that will be used from the new config file
 *     (Can have in string for array).
 */
function os2web_pagebuilder_update_entity_from_yml($module_name, $ymlFileName, $entityType, $id, array $setComponents) {
  $yml = Yaml::parse(file_get_contents(drupal_get_path('module', $module_name) . '/config/optional/' . $ymlFileName . '.yml'));

  $entity = \Drupal::entityTypeManager()
    ->getStorage($entityType)
    ->load($id);

  if (empty($entity)) {
    os2web_pagebuilder_read_in_new_config($ymlFileName, $module_name);
    return;
  }

  foreach ($setComponents as $key => $value) {
    $parts = explode('.', $value);
    if (count($parts) == 1) {
      $entity->setComponent($key, $yml[$value]);
    }
    else {
      $value = NestedArray::getValue($yml, $parts);
      if (empty($value)) {
        \Drupal::service('messenger')->addWarning('Component ' . $key . ' has empty configuration');
        continue;
      }
      $entity->setComponent($key, $value);
    }
  }

  $entity->save();
}

/**
 * Implements hook_form_alter().
 */
function os2web_pagebuilder_form_alter(&$form, FormStateInterface $form_state, $form_id) {
  // Hiding os2web_contact related fields, if setting tells us to.
  if ($form_id == 'node_os2web_page_form' || $form_id == 'node_os2web_page_edit_form') {
    if (\Drupal::config(SettingsForm::$configName)
      ->get('hide_os2web_contact_fields')) {
      $form['field_os2web_page_contact']['#access'] = FALSE;
      $form['field_os2web_page_contact_hide']['#access'] = FALSE;
    }

    if (\Drupal::config(SettingsForm::$configName)
      ->get('hide_os2web_paragraph_banner_field')) {
      $form['field_os2web_page_paragraph_bann']['#access'] = FALSE;
    }
    if (\Drupal::config(SettingsForm::$configName)
      ->get('hide_os2web_content_page_section_tab')) {
      $form['field_os2web_page_paragraph_righ']['#access'] = FALSE;
      $form['field_os2web_page_paragraph_left']['#access'] = FALSE;
    }
  }
}

/**
 * Implements hook_block_access().
 */
function os2web_pagebuilder_block_access(Block $block, $operation, AccountInterface $account) {
  // Hiding os2web_contact, if setting tells us to.
  if ($operation == 'view') {
    if ($block->getPluginId() == 'os2web_contact') {
      if (\Drupal::config(SettingsForm::$configName)->get('hide_os2web_contact_fields')) {
        return AccessResult::forbidden();
      }
    }
  }

  return AccessResult::neutral();
}

/**
 * Implements hook_field_widget_WIDGET_TYPE_form_alter().
 */
function os2web_pagebuilder_field_widget_paragraphs_form_alter(&$element, &$form_state, $context) {
  if (\Drupal::config(SettingsForm::$configName)
    ->get('hide_os2web_paragraph_title_field')) {
    switch ($element['#paragraph_type']) {
      case 'os2web_spotbox_reference':
        $element['subform']['field_os2web_spotbox_reference_h']['#access'] = FALSE;
        break;

      case 'os2web_accordion':
        $element['subform']['field_os2web_accordion_heading']['#access'] = FALSE;
        break;

      case 'os2web_banner_paragraph':
        $element['subform']['field_os2web_banner_heading']['#access'] = FALSE;
        break;

      case 'os2web_box_paragraph':
        $element['subform']['field_os2web_box_heading']['#access'] = FALSE;
        break;

      case 'os2web_files_paragraph':
        $element['subform']['field_os2web_files_heading']['#access'] = FALSE;
        break;

      case 'os2web_content_reference':
        $element['subform']['field_os2web_content_reference_h']['#access'] = FALSE;
        break;

      case 'os2web_simple_text_paragraph':
        $element['subform']['field_os2web_simple_text_heading']['#access'] = FALSE;
        break;

      case 'os2web_cnt_paragraph':
        $element['subform']['field_os2web_cnt_heading']['#access'] = FALSE;
        break;
    }
  }
  if (\Drupal::config(SettingsForm::$configName)
    ->get('hide_os2web_paragraph_subtitle_field')) {
    switch ($element['#paragraph_type']) {
      case 'os2web_spotbox_reference':
        $element['subform']['field_os2web_spotbox_ref_subhead']['#access'] = FALSE;
        break;

      case 'os2web_accordion':
        $element['subform']['field_os2web_accordion_subheadin']['#access'] = FALSE;
        break;

      case 'os2web_banner_paragraph':
        $element['subform']['field_os2web_banner_subheading']['#access'] = FALSE;
        break;

      case 'os2web_content_reference':
        $element['subform']['field_os2web_content_ref_subhead']['#access'] = FALSE;
        break;

      case 'os2web_simple_text_paragraph':
        $element['subform']['field_os2web_simple_text_subhead']['#access'] = FALSE;
        break;

      case 'os2web_cnt_paragraph':
        $element['subform']['field_os2web_cnt_subheading']['#access'] = FALSE;
        break;
    }
  }
}

/**
 * Get all pages that are using this section and are promoted.
 *
 * @param int $section_term_id
 *   Term ID of the section term.
 *
 * @return array
 *   Array of Node Ids.
 */
function getSectionPromotedNodes($section_term_id) {
  $query = \Drupal::entityQuery('node');
  $query->condition('status', 1);
  $query->condition('type', 'os2web_page');
  $query->condition('promote', 1);
  $query->condition('field_os2web_page_section', $section_term_id);

  return $query->execute();
}
