<?php

/**
 * @file
 * Page builder module.
 */

use Drupal\block\Entity\Block;
use Drupal\Component\Utility\NestedArray;
use Drupal\Core\Access\AccessResult;
use Drupal\Core\Form\FormStateInterface;
use Drupal\Core\Session\AccountInterface;
use Drupal\os2web_pagebuilder\Form\SettingsForm;
use Symfony\Component\Yaml\Yaml;

/**
 * Update entity from yml.
 *
 * Some config like form display needs to be updated via config manager.
 *
 * @param string $ymlFileName
 *   Yml file name.
 * @param string $entityType
 *   The entity type for this storage.
 * @param mixed $id
 *   The ID of the entity to load.
 * @param array $setComponents
 *   Array of components you want to add.
 *   - The key will be what we are setting.
 *   - The value is the key that will be used from the new config file
 *     (Can have in string for array).
 *
 * @throws
 */
function os2web_pagebuilder_update_entity_from_yml($module_name, $ymlFileName, $entityType, $id, array $setComponents) {
  $yml = Yaml::parse(file_get_contents(drupal_get_path('module', $module_name) . '/config/optional/' . $ymlFileName . '.yml'));

  $entity = \Drupal::entityTypeManager()
    ->getStorage($entityType)
    ->load($id);
  foreach ($setComponents as $key => $value) {
    $parts = explode('.', $value);
    if (count($parts) == 1) {
      $entity->setComponent($key, $yml[$value]);
    }
    else {
      $value = NestedArray::getValue($yml, $parts);
      if (empty($value)) {
        \Drupal::service('messenger')->addWarning('Component ' . $key . ' has empty configuration');
        continue;
      }
      $entity->setComponent($key, $value);
    }
  }

  $entity->save();
}

/**
 * Implements hook_form_FORM_ID_alter().
 */
function os2web_pagebuilder_form_node_os2web_page_edit_form_alter(&$form, FormStateInterface $form_state, $form_id) {
  // Hiding os2web_contact related fields, if setting tells us to.
  if (\Drupal::config(SettingsForm::$configName)->get('hide_os2web_contact_fields')) {
    $form['field_os2web_page_contact']['#access'] = FALSE;
    $form['field_os2web_page_contact_hide']['#access'] = FALSE;
  }
}

/**
 * Implements hook_block_access().
 */
function os2web_pagebuilder_block_access(Block $block, $operation, AccountInterface $account) {
  // Hiding os2web_contact, if setting tells us to.
  if ($operation == 'view') {
    if ($block->getPluginId() == 'os2web_contact') {
      if (\Drupal::config(SettingsForm::$configName)->get('hide_os2web_contact_fields')) {
        return AccessResult::forbidden();
      }
    }
  }

  return AccessResult::neutral();
}
