<?php

/**
 * @file
 * OS2Web accordion paragraph module file.
 */

/**
 * Implements hook_theme().
 */
function os2web_accordion_paragraph_theme($existing, $type, $theme, $path) {
  return [
    'paragraph__os2web_accordion' => [
      'base hook' => 'paragraph',
    ],
  ];
}

/**
 * Implements hook_preprocess_HOOK().
 */
function os2web_accordion_preprocess_paragraph(&$variables) {
  $i = 1;
}
