<?php

/**
 * @file
 * OS2Web accordion paragraph module file.
 */

use Drupal\Core\Render\Element;

/**
 * Implements hook_theme().
 */
function os2web_accordion_paragraph_theme($existing, $type, $theme, $path) {
  return [
    'paragraph__os2web_accordion' => [
      'base hook' => 'paragraph',
    ],
    'os2web_accordion' => [
      'render element' => 'elements',
    ],
  ];
}

/**
 * Implements hook_preprocess_HOOK().
 */
function os2web_accordion_preprocess_paragraph(&$variables) {
  $i = 1;
}

/**
 * Implements hook_theme_suggestions_HOOK().
 */
function os2web_accordion_paragraph_theme_suggestions_os2web_accordion(array $variables) {
  $suggestions = [];
  $os2web_accordion = $variables['elements']['#os2web_accordion'];
  $sanitized_view_mode = strtr($variables['elements']['#view_mode'], '.', '_');
  $suggestions[] = 'os2web_accordion__' . $sanitized_view_mode;
  $suggestions[] = 'os2web_accordion__' . $os2web_accordion->id();
  $suggestions[] = 'os2web_accordion__' . $os2web_accordion->id() . '__' . $sanitized_view_mode;

  return $suggestions;
}

/**
 * Prepares variables for OS2Web Accordion templates.
 *
 * Default template: os2web_accordion.html.twig.
 *
 * @param array $variables
 *   An associative array containing:
 *   - elements: An associative array containing the user information and any
 *   - attributes: HTML attributes for the containing element.
 */
function template_preprocess_os2web_accordion(array &$variables) {
  // Fetch Accordion Entity Object.
  $os2web_accordion = $variables['elements']['#os2web_accordion'];
  $variables['accordion'] = $os2web_accordion;

  // Helpful $content variable for templates.
  foreach (Element::children($variables['elements']) as $key) {
    $variables['content'][$key] = $variables['elements'][$key];
  }
}
