<?php

/**
 * @file
 * OS2Web contact form paragraph module file.
 */

/**
 * Implements hook_preprocess_HOOK().
 */
function os2web_contact_form_paragraph_preprocess_paragraph(&$variables) {
  $paragraph = $variables['paragraph'];
  if ($paragraph->bundle() != 'os2web_contact_form') {
    return;
  }

  $contact_form_values = $paragraph->field_os2web_contact_form_ref->getValue();

  if (!empty($contact_form_values[0]['target_id'])
    && $variables['view_mode'] != 'preview') {
    $entity_type_manager = \Drupal::service('entity_type.manager');
    $entity_form_builder = \Drupal::service('entity.form_builder');
    /** @var \Drupal\contact\Entity\ContactForm $contact_form */
    $contact_form = $entity_type_manager->getStorage('contact_form')->load($contact_form_values[0]['target_id']);

    /** @var \Drupal\contact\Entity\Message $contact_message */
    $contact_message = $entity_type_manager
      ->getStorage('contact_message')
      ->create(['contact_form' => $contact_form->id()]);
    if ($contact_message->isPersonal()) {
      return;
    }

    $form = $entity_form_builder->getForm($contact_message);
    $form['#cache']['contexts'][] = 'user.permissions';
    \Drupal::service('renderer')->addCacheableDependency($form, $contact_form);

    $form['#contextual_links']['contact_block'] = [
      'route_parameters' => ['contact_form' => $contact_form->id()],
    ];
    $variables['contact_form'] = $form;
  }
}

/**
 * Implements hook_theme().
 */
function os2web_contact_form_paragraph_theme($existing, $type, $theme, $path) {
  return [
    'paragraph__os2web_contact_form' => [
      'base hook' => 'paragraph',
    ],
  ];
}
