<?php

/**
 * @file
 * OS2Web box paragraph module file.
 */

/**
 * Implements hook_preprocess_HOOK().
 */
function os2web_box_paragraph_preprocess_paragraph(&$variables) {
  $paragraph = $variables['paragraph'];
  if ($paragraph->bundle() != 'os2web_box_paragraph') {
    return;
  }

  $bg_color_field_values = $paragraph->field_os2web_box_bg_color->getValue();
  if ($bg_color_field_values[0]['value']) {
    $variables['background_color'] = $bg_color_field_values[0]['value'];
  }
}

/**
 * Implements hook_theme().
 */
function os2web_box_paragraph_theme($existing, $type, $theme, $path) {
  return [
    'paragraph__os2web_box' => [
      'base hook' => 'paragraph',
    ],
  ];
}
