name: OS2Web pagebuilder build

on:
  push:
    branches:
    - "*"
  pull_request:
    branches:
    - master
    - develop

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
 
    - name: Cache Composer packages
      id: composer-cache
      uses: actions/cache@v2
      with:
        path: vendor
        key: ${{ runner.os }}-php-${{ hashFiles('**/composer.lock') }}
        restore-keys: |
          ${{ runner.os }}-php-

    - name: Prepare entivonment and codebase
      run: |
        composer global require drush/drush:8.x-dev drupal/coder mglaman/drupal-check friendsoftwig/twigcs
        cd ../ && composer create-project drupal-composer/drupal-project:9.x-dev drupal --no-interaction
        cd drupal
        export DRUPAL_ROOT=$(pwd)/web
        export REPOSITORIES='"repositories":\ \['
        export REPOSITORIES_REPLACE='"repositories":\[\{"type":"path","url":"..\/os2web_pagebuilder","options":\{"symlink":false\}\},'
        export REQUIRE='"require":\ {'
        export REQUIRE_REPLACE='"require":{"os2web\/os2web_pagebuilder":"\*",'
        sed -i "s/$REPOSITORIES/$REPOSITORIES_REPLACE/g" composer.json
        sed -i "s/$REQUIRE/$REQUIRE_REPLACE/g" composer.json
        composer update os2web/os2web_pagebuilder
        PROJECT_PATH=$DRUPAL_ROOT/web/modules/contrib/os2web_pagebuilder
        export PATH="$HOME/.composer/vendor/bin:$PATH"
        phpcs --config-set installed_paths ../../drupal/coder/coder_sniffer

    - name: Install Node dependencies
      uses: actions/setup-node@v2
      with:
        node-version: '14'
        cache: 'npm'
        cache-dependency-path: $DRUPAL_ROOT/core/package-lock.json

    - name: Install Node global packages
      run: |       
        cd $DRUPAL_ROOT/core
        npm install --global eslint-config-drupal-bundle stylelint
        
    - name: Run checks
      run: |
        phpcs --standard=Drupal --ignore=*.md $PROJECT_PATH
        twigcs $PROJECT_PATH

    - name: Install Drupal and activate module
      run: |
        ./vendor/bin/drush site-install --verbose --yes --db-url=sqlite://tmp/site.sqlite
        ./vendor/bin/drush --verbose en os2web_pagebuilder --yes
